[colors.bright]
black = "#686868"
blue = "#59C2FF"
cyan = "#95E6CB"
green = "#C2D94C"
magenta = "#FFEE99"
red = "#F07178"
white = "#FFFFFF"
yellow = "#FFB454"

[colors.normal]
black = "#01060E"
blue = "#53BDFA"
cyan = "#90E1C6"
green = "#91B362"
magenta = "#FAE994"
red = "#EA6C73"
white = "#C7C7C7"
yellow = "#F9AF4F"

[colors.primary]
background = "#31313a"
foreground = "#B3B1AD"

[font]
size = 21.0

[font.bold]
#family = "DejaVu Sans Mono"
family = "Iosevka Nerd Font Mono"
style = "Bold"

[font.bold_italic]
#family = "DejaVu Sans Mono"
family = "Iosevka Nerd Font Mono"
style = "Bold Italic"

[font.italic]
#family = "DejaVu Sans Mono"
family = "Iosevka Nerd Font Mono"
style = "Italic"

[font.normal]
#family = "DejaVu Sans Mono"
family = "Iosevka Nerd Font Mono"
style = "Regular"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.8
startup_mode = "Maximized"

[window.padding]
x = 4
y = 4
